// Port of asmcomp/branch_relaxation.ml (and branch_relaxation_intf.mli):
// the relaxation of conditional branches whose targets are out of range,
// for the targets whose emitter uses it (arm64).  [T] is the target's Size
// module (Branch_relaxation_intf.S): CondBranch, all, max_displacement,
// classify_instr, offset_pc_at_branch, instr_size and the relax_* rewrites.
#pragma once

#include <algorithm>
#include <climits>
#include <stdexcept>
#include <unordered_map>

#include "cppcaml/typing/linear.hpp"

namespace cppcaml::typing::branch_relaxation {

// [instr.desc <- d]: the instruction description and its payload
inline void set_desc(linear::Instruction& i, const linear::Instruction& d) {
  i.desc = d.desc;
  i.op = d.op;
  i.lbl = d.lbl;
  i.test = d.test;
  i.lbl0 = d.lbl0;
  i.lbl1 = d.lbl1;
  i.lbl2 = d.lbl2;
  i.lbls = d.lbls;
  i.delta_traps = d.delta_traps;
  i.raise = d.raise;
}

// Linear.instr_cons
inline linear::Instr instr_cons(const linear::Instruction& d, const reg::Regs& a, const reg::Regs& r,
                                linear::Instr n) {
  auto* i = make<linear::Instruction>();
  set_desc(*i, d);
  i->next = n;
  i->arg = a;
  i->res = r;
  i->dbg = debuginfo::none();
  return i;
}

template <class T>
struct Make {
  using Instruction = linear::Instruction;
  using LK = Instruction::K;
  using MK = mach::Operation::K;
  using IO = mach::IntegerOperation;
  using LabelMap = std::unordered_map<long, long>;

  static std::pair<long, LabelMap> label_map(const linear::Fundecl& f) {
    LabelMap map;
    long pc = 0;
    for (linear::Instr i = f.fun_body;; i = i->next) {
      if (i->desc == LK::Lend) return {pc, map};
      if (i->desc == LK::Llabel) map.emplace(i->lbl, pc);
      else pc += T::instr_size(f, *i);
    }
  }

  static bool branch_overflows(const LabelMap& map, long pc_branch, long lbl_dest, long max_branch_offset) {
    auto it = map.find(lbl_dest);
    if (it == map.end()) throw std::out_of_range("Branch_relaxation: Not_found");
    long delta = it->second - (pc_branch + T::offset_pc_at_branch);
    return delta <= -max_branch_offset || delta >= max_branch_offset;
  }

  static bool opt_branch_overflows(const LabelMap& map, long pc_branch, const std::optional<long>& opt_lbl_dest,
                                   long max_branch_offset) {
    return opt_lbl_dest && branch_overflows(map, pc_branch, *opt_lbl_dest, max_branch_offset);
  }

  static bool instr_overflows(long code_size, long max_out_of_line_code_offset, const Instruction& instr,
                              const LabelMap& map, long pc) {
    auto branch = T::classify_instr(instr);
    if (!branch) return false;
    // Remember to cut some slack for multi-word instructions (in the
    // [Linear] sense of the word) where the branch can be anywhere in the
    // middle.  12 words of slack is plenty.
    long max_branch_offset = T::max_displacement(*branch) - 12;
    switch (instr.desc) {
      case LK::Lop: {
        const mach::Operation& op = *instr.op;
        if (op.k == MK::Ipoll && op.return_label)
          // A poll-and-branch instruction can branch to the label lbl, but
          // also to an out-of-line code block.
          return code_size + max_out_of_line_code_offset - pc >= max_branch_offset ||
                 branch_overflows(map, pc, *op.return_label, max_branch_offset);
        if (op.k == MK::Ialloc || op.k == MK::Ipoll || op.k == MK::Ispecific ||
            ((op.k == MK::Iintop || op.k == MK::Iintop_imm) && op.intop.op == IO::Icheckbound))
          // We assume that any branches eligible for relaxation generated by
          // these instructions only branch forward.  We further assume that
          // any of these may branch to an out-of-line code block.
          return code_size + max_out_of_line_code_offset - pc >= max_branch_offset;
        break;
      }
      case LK::Lcondbranch: return branch_overflows(map, pc, instr.lbl, max_branch_offset);
      case LK::Lcondbranch3:
        return opt_branch_overflows(map, pc, instr.lbl0, max_branch_offset) ||
               opt_branch_overflows(map, pc, instr.lbl1, max_branch_offset) ||
               opt_branch_overflows(map, pc, instr.lbl2, max_branch_offset);
      default: break;
    }
    throw std::runtime_error("Unsupported instruction for branch relaxation");
  }

  static linear::Instr expand_optbranch(const std::optional<long>& lbl, long n, const reg::Regs& arg,
                                        linear::Instr next) {
    if (!lbl) return next;
    Instruction d{LK::Lcondbranch};
    d.test = mach::Test{mach::Test::K::Iinttest_imm, {true, lambda::IntegerComparison::Ceq}, n};
    d.lbl = *lbl;
    return instr_cons(d, arg, {}, next);
  }

  static Instruction lop(const mach::Operation& op) {
    Instruction d{LK::Lop};
    d.op = mach::op_ref(op);
    return d;
  }

  static bool fixup_branches(long code_size, long max_out_of_line_code_offset, const LabelMap& map,
                             const linear::Fundecl& f) {
    bool did_fix = false;
    long pc = 0;
    linear::Instr instr = f.fun_body;
    for (;;) {
      if (instr->desc == LK::Lend) return did_fix;
      if (!instr_overflows(code_size, max_out_of_line_code_offset, *instr, map, pc)) {
        pc += T::instr_size(f, *instr);
        instr = instr->next;
        continue;
      }
      did_fix = true;
      switch (instr->desc) {
        case LK::Lop: {
          const mach::Operation& op = *instr->op;
          if (op.k == MK::Ipoll) set_desc(*instr, lop(T::relax_poll(op.return_label)));
          else if (op.k == MK::Ialloc) set_desc(*instr, lop(T::relax_allocation(op.n, op.dbginfo)));
          else if (op.k == MK::Iintop && op.intop.op == IO::Icheckbound) set_desc(*instr, lop(T::relax_intop_checkbound()));
          else if (op.k == MK::Iintop_imm && op.intop.op == IO::Icheckbound)
            set_desc(*instr, lop(T::relax_intop_imm_checkbound(op.n)));
          else if (op.k == MK::Ispecific) set_desc(*instr, lop(T::relax_specific_op(op.spec)));
          else throw std::logic_error("Branch_relaxation.fixup_branches");
          pc += T::instr_size(f, *instr);
          instr = instr->next;
          break;
        }
        case LK::Lcondbranch: {
          long lbl2 = cmm::new_label();
          Instruction br{LK::Lbranch};
          br.lbl = instr->lbl;
          Instruction lab{LK::Llabel};
          lab.lbl = lbl2;
          linear::Instr cont = instr_cons(br, {}, {}, instr_cons(lab, {}, {}, instr->next));
          instr->test = linear::invert_test(instr->test);
          instr->lbl = lbl2;
          instr->next = cont;
          pc += T::instr_size(f, *instr);
          instr = instr->next;
          break;
        }
        case LK::Lcondbranch3: {
          linear::Instr cont =
              expand_optbranch(instr->lbl0, 0, instr->arg,
                               expand_optbranch(instr->lbl1, 1, instr->arg,
                                                expand_optbranch(instr->lbl2, 2, instr->arg, instr->next)));
          set_desc(*instr, *cont);
          instr->next = cont->next;
          break;  // fixup true pc instr
        }
        default:
          // Any other instruction has already been rejected in
          // [instr_overflows] above.
          throw std::logic_error("Branch_relaxation.fixup_branches: assert false");
      }
    }
  }

  // Iterate branch expansion till all conditional branches are OK
  static void relax(const linear::Fundecl& f, long max_out_of_line_code_offset) {
    long min_of_max_branch_offsets = LONG_MAX;
    for (auto b : T::all) min_of_max_branch_offsets = std::min(min_of_max_branch_offsets, T::max_displacement(b));
    for (;;) {
      auto [code_size, map] = label_map(f);
      if (!(code_size >= min_of_max_branch_offsets && fixup_branches(code_size, max_out_of_line_code_offset, map, f)))
        return;
    }
  }
};

}  // namespace cppcaml::typing::branch_relaxation
