#!/usr/bin/env bash
# Regenerate c++ocamlc's driver tables from ocamlc's compiler-libs (the
# C++ analogue of evaluating Main_args / Config / Warnings in ocamlc):
#   cxx/src/typing/main_args_table.inc   the bytecomp option list
#   cxx/src/typing/config_table.inc      Config.print_config's variables
#   cxx/src/typing/warning_descriptions.inc  Warnings.descriptions
# Run after `make` whenever driver/main_args.ml, utils/config*.ml or
# utils/warnings.ml change.
set -eu
R="$(cd "$(dirname "$(readlink -f "$0")")/../.." && pwd)"
T=$(mktemp -d)
trap 'rm -rf "${T:?}"' EXIT
cp "$R/cxx/harness/gen_driver_tables.ml" "$T/"
( cd "$T" && "$R/ocamlc.opt" -nostdlib -I "$R/stdlib" -I "$R/compilerlibs" -I "$R/utils" \
    -I "$R/parsing" -I "$R/typing" -I "$R/driver" -I "$R/bytecomp" -I "$R/lambda" -I "$R/file_formats" \
    "$R/compilerlibs/ocamlcommon.cma" "$R/compilerlibs/ocamlbytecomp.cma" gen_driver_tables.ml -o gen )
hdr="// Generated by cxx/harness/gen_driver_tables.sh from ocamlc's compiler-libs: do not edit."
{ echo "$hdr"; "$R/runtime/ocamlrun" "$T/gen" options; } > "$R/cxx/src/typing/main_args_table.inc"
{ echo "$hdr"; "$R/runtime/ocamlrun" "$T/gen" config; } > "$R/cxx/src/typing/config_table.inc"
{ echo "$hdr"; "$R/runtime/ocamlrun" "$T/gen" warnings; } > "$R/cxx/src/typing/warning_descriptions.inc"
