#!/usr/bin/env bash
# Regenerate c++ocamlc's driver tables from the tree's compiler-libs (the
# C++ analogue of evaluating Main_args / Warnings in ocamlc):
#   cxx/src/typing/main_args_table.inc      the bytecomp option list
#   cxx/src/typing/optmain_args_table.inc   the optcomp (ocamlopt) option list
#   cxx/src/typing/warning_descriptions.inc Warnings.descriptions
# Run after `make` whenever driver/main_args.ml or utils/warnings.ml change.
# (These come from the sources, the same for every configuration; the
# configuration's tables are cxx/Makefile's: cxx/src/tools/gen_config.cpp.)
set -eu
SELF="$(cd "$(dirname "$0")" && pwd -P)/$(basename "$0")"
. "$(dirname "$SELF")/portable.sh"
R="$(cd "$(dirname "$SELF")/../.." && pwd -P)"
T=$(mktemp -d)
trap 'rm -rf "${T:?}"' EXIT
cp "$R/cxx/harness/gen_driver_tables.ml" "$T/"
( cd "$T" && "$R/ocamlc.opt" -nostdlib -I "$R/stdlib" -I "$R/compilerlibs" -I "$R/utils" \
    -I "$R/parsing" -I "$R/typing" -I "$R/driver" -I "$R/bytecomp" -I "$R/lambda" -I "$R/file_formats" \
    "$R/compilerlibs/ocamlcommon.cma" "$R/compilerlibs/ocamlbytecomp.cma" gen_driver_tables.ml -o gen )
run() { "$R/runtime/ocamlrun" "$T/gen" "$@"; }
hdr="// Generated by cxx/harness/gen_driver_tables.sh from ocamlc's compiler-libs: do not edit."
{ echo "$hdr"; run options; } > "$R/cxx/src/typing/main_args_table.inc"
{ echo "$hdr"; run optoptions; } > "$R/cxx/src/typing/optmain_args_table.inc"
{ echo "$hdr"; run warnings; } > "$R/cxx/src/typing/warning_descriptions.inc"
