#!/usr/bin/env bash
# Regenerate c++ocamlc's driver tables from ocamlc's compiler-libs (the
# C++ analogue of evaluating Main_args / Config / Warnings in ocamlc):
#   cxx/src/typing/main_args_table.inc   the bytecomp option list
#   cxx/src/typing/optmain_args_table.inc   the optcomp (ocamlopt) option list
#   cxx/src/typing/config_table.inc      Config.print_config's variables
#   cxx/src/typing/warning_descriptions.inc  Warnings.descriptions
#   cxx/include/cppcaml/typing/config_link.inc  the Config values the linker reads
# Run after `make` whenever driver/main_args.ml, utils/config*.ml or
# utils/warnings.ml change.
#
# INSTALL=<prefix> configures c++ocamlc for an installed OCaml of this
# version instead of the build tree (an opam switch, say: its bin/ocamlc.opt
# and lib/ocaml/compiler-libs), to replace that installation's ocamlc.  The
# generator is then a native program: a bytecode one would see the
# standard library directory its linker recorded, resolved, where ocamlc
# configured --with-relative-libdir keeps it relative -- that one value
# (standard_library_relative) is taken from the installed ocamlc itself.
set -eu
R="$(cd "$(dirname "$0")/../.." && pwd -P)"
. "$R/cxx/harness/portable.sh"
T=$(mktemp -d)
trap 'rm -rf "${T:?}"' EXIT
cp "$R/cxx/harness/gen_driver_tables.ml" "$T/"
if [ -n "${INSTALL:-}" ]; then
  L="$INSTALL/lib/ocaml"
  ( cd "$T" && "$INSTALL/bin/ocamlopt.opt" -I "$L/compiler-libs" \
      "$L/compiler-libs/ocamlcommon.cmxa" "$L/compiler-libs/ocamlbytecomp.cmxa" gen_driver_tables.ml -o gen )
  run() { "$T/gen" "$@"; }
  rel=$("$INSTALL/bin/ocamlc.opt" -config-var standard_library_relative 2>/dev/null || true)
else
  ( cd "$T" && "$R/ocamlc.opt" -nostdlib -I "$R/stdlib" -I "$R/compilerlibs" -I "$R/utils" \
      -I "$R/parsing" -I "$R/typing" -I "$R/driver" -I "$R/bytecomp" -I "$R/lambda" -I "$R/file_formats" \
      "$R/compilerlibs/ocamlcommon.cma" "$R/compilerlibs/ocamlbytecomp.cma" gen_driver_tables.ml -o gen )
  run() { "$R/runtime/ocamlrun" "$T/gen" "$@"; }
  rel=""
fi
hdr="// Generated by cxx/harness/gen_driver_tables.sh from ocamlc's compiler-libs: do not edit."
{ echo "$hdr"; run options; } > "$R/cxx/src/typing/main_args_table.inc"
{ echo "$hdr"; run optoptions; } > "$R/cxx/src/typing/optmain_args_table.inc"
{ echo "$hdr"; run config | sed "s|^    {\"standard_library_relative\", \"[^\"]*\"},|    {\"standard_library_relative\", \"$rel\"},|"; } \
  > "$R/cxx/src/typing/config_table.inc"
{ echo "$hdr"; run warnings; } > "$R/cxx/src/typing/warning_descriptions.inc"
{ echo "$hdr"; run linkconfig; } > "$R/cxx/include/cppcaml/typing/config_link.inc"
