#!/usr/bin/env bash
# Check the generated parser checked in under boot/menhir/ against its source.
#
# The build compiles boot/menhir/parser.ml (and Menhir's runtime library,
# boot/menhir/menhirLib.ml), not parsing/parser.mly: the parser is generated
# code that ships in the repository, 3 MB of it, most of the automaton encoded
# in binary strings.  The compiler DDC (ddc.sh) shows that file is COMPILED
# faithfully; this check shows it is what the grammar says.  It regenerates the
# four files as `make promote-menhir` does and compares them byte for byte:
#
#   menhirLib.ml{,i}  Menhir's runtime library, imported as this branch's
#                     promote-menhir does (`menhir --dump-menhirLib`, or a copy
#                     of the files Menhir installs)
#   parser.ml{,i}     Menhir run on parsing/parser.mly with the Makefile's flags,
#                     its --infer types taken twice: from boot/ocamlc (the
#                     recipe's compiler) and from c++ocamlc (diverse: no type the
#                     bootstrap binary computed reaches the parser)
#
# It needs the Menhir release the parser was generated with (the version
# boot/menhir/parser.ml requires): MENHIR=<that menhir>.  An opam-installed
# Menhir of that version does, where the recipe dumps menhirLib; otherwise:
#   opam source menhir.<version> --dir=/tmp/menhir-<version>
#   (cd /tmp/menhir-<version> && dune build -p menhirLib,menhirSdk,menhir)
#   MENHIR=/tmp/menhir-<version>/_build/install/default/bin/menhir
# What stays trusted: Menhir itself (an OCaml program, built by the host's OCaml)
# and awk/sed.
#
# Usage:   MENHIR=<menhir> bash cxx/harness/menhir_check.sh
set -u
set -o pipefail
SELF="$(readlink -f "$0")"
cd "$(dirname "$SELF")/../.." || exit 1
ROOT=$PWD
source cxx/harness/_require_fresh.sh; require_fresh c++ocamlc
CPPC=$ROOT/cxx/build/c++ocamlc
die() { echo "FATAL: $*" >&2; exit 1; }

# --- the Menhir release the checked-in parser was generated with -------------
want=$(sed -n 's/.*MenhirLib\.StaticVersion\.require_\([0-9]*\).*/\1/p' boot/menhir/parser.ml | head -1)
[ -n "$want" ] || die "no MenhirLib version requirement in boot/menhir/parser.ml"
M=${MENHIR:-menhir}
command -v "$M" >/dev/null || die "no menhir (set MENHIR=; see the header for building menhir $want)"
have=$("$M" --version 2>/dev/null | sed -n 's/.*version \([0-9]*\).*/\1/p')
[ "$have" = "$want" ] || die "boot/menhir was generated by menhir $want, $M is $have (see the header)"
echo "menhir $have = $M"

OUT=$(mktemp -d /tmp/menhir_check.XXXXXX)
same=0 diff=0 difl=""
check() {   # generated reference
  if cmp -s "$1" "$2"; then same=$((same+1)); echo "  same  $2"
  else diff=$((diff+1)); difl="$difl $2"; echo "  DIFF  $2"; fi
}

# --- promote-menhir's own commands (this branch's Makefile) ------------------
recipe=$(make -s -n -f Makefile promote-menhir MENHIR=MENHIR_CMD 2>/dev/null)
cmd=$(grep '^MENHIR_CMD .*parsing/parser\.mly' <<< "$recipe" | head -1)
[ -n "$cmd" ] || die "could not read promote-menhir's menhir command from the Makefile"

# --- menhirLib: as promote-menhir imports it ------------------------------------
echo "== menhirLib =="
if grep -q '^MENHIR_CMD --dump-menhirLib' <<< "$recipe"; then
  # newer Menhir writes its runtime library's source itself
  libdir=$OUT/lib; mkdir -p "$libdir"
  "$M" --dump-menhirLib "$libdir/" >/dev/null 2>&1 || die "menhir --dump-menhirLib failed"
  echo "  (menhir --dump-menhirLib, as this branch's promote-menhir does)"
else
  # promote-menhir copies the files Menhir installs; a dune build tree keeps
  # them in lib/pack (an opam install may hold only compiled modules)
  libdir=$("$M" --suggest-menhirLib 2>/dev/null)
  if ! [ -f "$libdir/menhirLib.ml" ] || head -1 "$libdir/menhirLib.ml" | grep -q 'generated by dune'; then
    p=$(command -v "$M")
    case "$p" in */_build/*) libdir=${p%%/_build/*}/_build/default/lib/pack;; esac
  fi
  if ! [ -f "$libdir/menhirLib.ml" ] || head -1 "$libdir/menhirLib.ml" | grep -q 'generated by dune'; then
    die "no menhirLib.ml source for $M (build menhir from source; see the header)"
  fi
  echo "  (copied from $libdir, as this branch's promote-menhir does)"
fi
for f in ml mli; do check "$libdir/menhirLib.$f" "boot/menhir/menhirLib.$f"; done

# --- parser: promote-menhir's menhir command, writing into $OUT ---------------
bootoc="./boot/ocamlrun ./boot/ocamlc"
case "$cmd" in *"$bootoc"*) ;; *) die "promote-menhir's --ocamlc is not '$bootoc'";; esac
for infer in boot c++ocamlc; do
  o=$OUT/$infer; mkdir -p "$o"
  c=${cmd/MENHIR_CMD/\"$M\"}
  [ $infer = c++ocamlc ] && c=${c/$bootoc/$CPPC}
  c=${c/ parsing\/parser.mly/ --base $o\/parser parsing\/parser.mly}
  echo "== parser (--infer by $infer) =="
  eval "$c" >"$o/menhir.log" 2>&1 || { tail -5 "$o/menhir.log"; die "menhir failed"; }
  for f in ml mli; do
    # promote-menhir's normalization of Menhir's standard library path, and the
    # file's own name as Menhir writes it in line directives (parsing/ there)
    sed -e 's,^#\(.*\)"[^"]*/menhir/standard.mly",#\1"menhir/standard.mly",g' \
        -e "s,\"$o/parser\.$f\",\"parsing/parser.$f\",g" "$o/parser.$f" > "$o/parser.norm.$f"
    check "$o/parser.norm.$f" "boot/menhir/parser.$f"
  done
done

echo "=============================================================="
echo "MENHIR CHECK RESULT:  same=$same diff=$diff  (menhir $have; work dir $OUT)"
[ -n "$difl" ] && echo "  DIFF:$difl"
echo "=============================================================="
if [ "$diff" -eq 0 ] && [ "$same" -eq 6 ]; then
  echo "PASS: boot/menhir is exactly menhir $have's output for parsing/parser.mly"
  echo "      (menhirLib.ml{,i}; parser.ml{,i} with boot/ocamlc's and with c++ocamlc's --infer)."
  exit 0
else
  echo "FAIL: boot/menhir differs from menhir $have's output."
  exit 1
fi
