#!/bin/sh
# c++ocamlc as an opam switch's ocamlc: the step ocaml-variants.opam runs
# when ocaml-option-cxx is installed (cxx/INSTALL.md).
#
#   build-cxx.sh <prefix> <jobs>
#     in the build stage, in the source tree after `make` and
#     `make INSTALL_MODE=opam install` (which wrote ocaml-variants.install):
#     1. mimalloc's allocator override from the extra-source tarball;
#     2. the tree installed into a stage (make install DESTDIR=): the
#        installation is --with-relative-libdir, so a staged copy resolves
#        its standard library as the real one will;
#     3. c++ocamlc built with the host's C++ toolchain (CXX, default
#        clang++ >= 18), its driver tables generated from the staged OCaml
#        (Config, Main_args, warnings -- cxx/harness/gen_driver_tables.sh
#        INSTALL=), linking the installation's shared libzstd when its OCaml
#        compresses;
#     4. checked in the stage: the same libzstd file as the runtime's,
#        `-config` identical to the stock ocamlc's, a program compiled and
#        run;
#     5. ocaml-variants.install rewritten so that opam installs c++ocamlc as
#        bin/ocamlc.opt (bin/ocamlc points at it) and the stock compiler as
#        bin/ocamlc.stock.
set -eu
here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/../.." && pwd)
build="$root/cxx/_opam_build"
mi_src="$root/_opam_mimalloc_src"
mi_build="$root/_opam_mimalloc_build"
mi_pfx="$root/_opam_mimalloc"
say() { echo "build-cxx.sh: $*" >&2; }
die() { say "error: $*"; exit 1; }

zstd_libs() { sed -n 's/^ZSTD_LIBS=//p' "$root/Makefile.config"; }

cmake_zstd_args() {  # <staged bin dir>
  if [ -n "$(zstd_libs)" ]; then
    # the very libzstd the installation's runtime loads (same compressor
    # code, hence the same bytes), and zstd.h where the C compiler that
    # built the runtime finds it
    so=$(ldd "$1/ocamlrun" 2>/dev/null | sed -n 's/.*libzstd[^ ]* => \([^ ]*\).*/\1/p' | head -1)
    [ -n "$so" ] && [ -e "$so" ] || so=$("${CC:-cc}" -print-file-name=libzstd.so)
    inc=$(printf '#include <zstd.h>\n' | "${CC:-cc}" -E -x c - 2>/dev/null |
          sed -n 's|^# [0-9]* "\(.*\)/zstd\.h".*|\1|p' | head -1)
    [ -n "$inc" ] && [ -f "$inc/zstd.h" ] || die "this OCaml compresses with zstd but zstd.h was not found (install libzstd's development files)"
    [ -e "$so" ] || die "this OCaml compresses with zstd but its shared libzstd was not found"
    echo "-DCPPCAML_ZSTD=ON -DZSTD_INCLUDE_DIR=$inc -DZSTD_LIBRARY=$(readlink -f "$so")"
  else
    echo "-DCPPCAML_ZSTD=OFF"
  fi
}

do_build() {
  prefix=$1 jobs=$2
  CXX=${CXX:-clang++}
  command -v "$CXX" >/dev/null || die "no C++ compiler ($CXX); c++ocamlc needs clang++ >= 18 (C++23)"
  command -v cmake >/dev/null || die "cmake is required"
  command -v ninja >/dev/null || die "ninja is required"
  [ -x "$root/ocamlopt.opt" ] || die "c++ocamlc's configuration is generated by a native program: the native compiler is required"
  # 1. mimalloc (c++ocamlc's speed depends on it)
  tarball=$(ls "$root"/mimalloc-v*.tar.gz 2>/dev/null | head -1)
  mi_args="-DCPPCAML_MIMALLOC=OFF"
  if [ -n "$tarball" ]; then
    rm -rf "$mi_src" "$mi_build" "$mi_pfx"
    mkdir -p "$mi_src"
    tar xzf "$tarball" -C "$mi_src" --strip-components=1
    cmake -S "$mi_src" -B "$mi_build" -G Ninja -DCMAKE_BUILD_TYPE=Release \
      -DMI_BUILD_SHARED=OFF -DMI_BUILD_STATIC=ON -DMI_BUILD_OBJECT=ON -DMI_BUILD_TESTS=OFF \
      -DCMAKE_INSTALL_PREFIX="$mi_pfx" >/dev/null
    ninja -C "$mi_build" -j "$jobs" install >/dev/null
    obj=$(find "$mi_pfx" -name mimalloc.o | head -1)
    hdr=$(find "$mi_pfx" -name mimalloc.h | head -1)
    [ -n "$obj" ] && [ -n "$hdr" ] || die "mimalloc built no override object"
    mi_args="-DCPPCAML_MIMALLOC=ON -DMIMALLOC_OBJECT=$obj -DMIMALLOC_INCLUDE_DIR=$(dirname "$hdr")"
  else
    say "warning: no mimalloc tarball: building without mimalloc (slower)"
  fi
  # 2. the stage
  stage="$root/_opam_stage"
  rm -rf "$stage"
  make -C "$root" install DESTDIR="$stage" >/dev/null
  sp="$stage$prefix"
  sbin="$sp/bin"
  [ -x "$sbin/ocamlc.opt" ] || die "the staged installation has no bin/ocamlc.opt"
  # 3. c++ocamlc for this installation
  INSTALL="$sp" "$root/cxx/harness/gen_driver_tables.sh"
  zstd_args=$(cmake_zstd_args "$sbin") || exit 1
  # shellcheck disable=SC2086
  cmake -S "$root/cxx" -B "$build" -G Ninja -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_COMPILER="$CXX" $mi_args $zstd_args >/dev/null
  ninja -C "$build" -j "$jobs" c++ocamlc
  new="$build/c++ocamlc"
  # 4. the checks, in the stage
  if [ -n "$(zstd_libs)" ] && command -v ldd >/dev/null; then
    zr=$(ldd "$sbin/ocamlrun" 2>/dev/null | sed -n 's/.*libzstd[^ ]* => \([^ ]*\).*/\1/p')
    zc=$(ldd "$new" 2>/dev/null | sed -n 's/.*libzstd[^ ]* => \([^ ]*\).*/\1/p')
    if [ -n "$zr" ] && [ "$(readlink -f "$zr")" != "$(readlink -f "$zc")" ]; then
      die "libzstd mismatch: the runtime loads $zr, c++ocamlc $zc (compressed artifacts would differ)"
    fi
  fi
  cp "$sbin/ocamlc.opt" "$sbin/ocamlc.stock"
  cp "$new" "$sbin/ocamlc.opt"
  t=$(mktemp -d)
  "$sbin/ocamlc.stock" -config > "$t/stock.config"
  "$sbin/ocamlc.opt" -config > "$t/cxx.config" || die "c++ocamlc -config failed"
  if ! cmp -s "$t/stock.config" "$t/cxx.config"; then
    diff "$t/stock.config" "$t/cxx.config" >&2 || true
    die "c++ocamlc's -config differs from the stock ocamlc's"
  fi
  printf 'let () = print_endline (String.concat " " ["hello"; "from"; "c++ocamlc"])\n' > "$t/hello.ml"
  ( cd "$t" && "$sbin/ocamlc" hello.ml -o hello.byte && "$sbin/ocamlrun" ./hello.byte > out ) ||
    die "c++ocamlc could not compile and run a program"
  [ "$(cat "$t/out")" = "hello from c++ocamlc" ] || die "the compiled program printed the wrong thing"
  rm -rf "$t"
  # 5. opam installs c++ocamlc as ocamlc.opt, the stock one as ocamlc.stock
  inst="$root/ocaml-variants.install"
  [ -f "$inst" ] || die "no ocaml-variants.install (make INSTALL_MODE=opam install must run first)"
  grep -q '^  "ocamlc.opt"$' "$inst" || die "ocaml-variants.install has no bin entry for ocamlc.opt"
  sed -i 's|^  "ocamlc.opt"$|  "cxx/_opam_build/c++ocamlc" {"ocamlc.opt"}\
  "ocamlc.opt" {"ocamlc.stock"}|' "$inst"
  say "c++ocamlc will be installed as bin/ocamlc.opt (the stock compiler as bin/ocamlc.stock)"
}

case "${1:-}" in
  /*) do_build "$1" "${2:-1}" ;;
  *) die "usage: build-cxx.sh <prefix> <jobs>" ;;
esac
