#!/bin/sh
# c++ocamlc as an opam switch's ocamlc: the steps ocaml-variants.opam runs
# when ocaml-option-cxx is installed (cxx/INSTALL.md).
#
#   build-cxx.sh build <jobs>
#       (build stage, in the source tree after `make`) mimalloc's override
#       object from the extra-source tarball, then c++ocamlc with the host's
#       C++ toolchain (CXX, default clang++), linking the installation's
#       libzstd when its OCaml compresses;
#   build-cxx.sh install <prefix> <jobs>
#       (install stage, after the tree's own fixup installed the compiler)
#       c++ocamlc's driver tables regenerated from the INSTALLED OCaml
#       (Config, Main_args, warnings -- cxx/harness/gen_driver_tables.sh
#       INSTALL=), relinked; checked (same libzstd as the runtime, `-config`
#       identical to the stock ocamlc's, a program compiled and run); then
#       installed as bin/ocamlc.opt (bin/ocamlc points at it), the stock one
#       kept as bin/ocamlc.stock.
set -eu
here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/../.." && pwd)
build="$root/cxx/_opam_build"
mi_src="$root/_opam_mimalloc_src"
mi_build="$root/_opam_mimalloc_build"
mi_pfx="$root/_opam_mimalloc"
say() { echo "build-cxx.sh: $*" >&2; }
die() { say "error: $*"; exit 1; }

zstd_libs() { sed -n 's/^ZSTD_LIBS=//p' "$root/Makefile.config"; }

cmake_zstd_args() {
  if [ -n "$(zstd_libs)" ]; then
    # the SHARED library, the one the OCaml runtime loads: the same
    # compressor code, hence the same bytes
    inc=$(pkg-config --variable=includedir libzstd 2>/dev/null || echo /usr/include)
    lib=$(pkg-config --variable=libdir libzstd 2>/dev/null || echo /usr/lib)
    [ -f "$inc/zstd.h" ] || die "this OCaml compresses with zstd but zstd.h is not in $inc (install libzstd's development files)"
    so=""
    for c in "$lib/libzstd.so" "$lib/libzstd.so.1"; do [ -e "$c" ] && { so=$c; break; }; done
    [ -n "$so" ] || die "no shared libzstd in $lib"
    echo "-DCPPCAML_ZSTD=ON -DZSTD_INCLUDE_DIR=$inc -DZSTD_LIBRARY=$so"
  else
    echo "-DCPPCAML_ZSTD=OFF"
  fi
}

do_build() {
  jobs=$1
  CXX=${CXX:-clang++}
  command -v "$CXX" >/dev/null || die "no C++ compiler ($CXX); c++ocamlc needs clang++ >= 18 (C++23)"
  command -v cmake >/dev/null || die "cmake is required"
  command -v ninja >/dev/null || die "ninja is required"
  # mimalloc's allocator override (c++ocamlc's speed depends on it)
  tarball=$(ls "$root"/mimalloc-v*.tar.gz 2>/dev/null | head -1)
  mi_args="-DCPPCAML_MIMALLOC=OFF"
  if [ -n "$tarball" ]; then
    rm -rf "$mi_src" "$mi_build" "$mi_pfx"
    mkdir -p "$mi_src"
    tar xzf "$tarball" -C "$mi_src" --strip-components=1
    cmake -S "$mi_src" -B "$mi_build" -G Ninja -DCMAKE_BUILD_TYPE=Release \
      -DMI_BUILD_SHARED=OFF -DMI_BUILD_STATIC=ON -DMI_BUILD_OBJECT=ON -DMI_BUILD_TESTS=OFF \
      -DCMAKE_INSTALL_PREFIX="$mi_pfx" >/dev/null
    ninja -C "$mi_build" -j "$jobs" install >/dev/null
    obj=$(find "$mi_pfx" -name mimalloc.o | head -1)
    hdr=$(find "$mi_pfx" -name mimalloc.h | head -1)
    [ -n "$obj" ] && [ -n "$hdr" ] || die "mimalloc built no override object"
    mi_args="-DCPPCAML_MIMALLOC=ON -DMIMALLOC_OBJECT=$obj -DMIMALLOC_INCLUDE_DIR=$(dirname "$hdr")"
  else
    say "warning: no mimalloc tarball: building without mimalloc (slower)"
  fi
  # shellcheck disable=SC2046
  cmake -S "$root/cxx" -B "$build" -G Ninja -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_COMPILER="$CXX" $mi_args $(cmake_zstd_args) >/dev/null
  ninja -C "$build" -j "$jobs" c++ocamlc
}

do_install() {
  prefix=$1 jobs=$2
  bin="$prefix/bin"
  [ -x "$bin/ocamlc.opt" ] || die "$bin/ocamlc.opt is missing (the compiler is not installed yet)"
  [ -x "$bin/ocamlopt.opt" ] || die "c++ocamlc's configuration is generated by a native program: the native compiler is required"
  [ -f "$bin/ocamlc.stock" ] || cp "$bin/ocamlc.opt" "$bin/ocamlc.stock"
  # the driver tables of THIS installation, and the relinked compiler
  INSTALL="$prefix" "$root/cxx/harness/gen_driver_tables.sh"
  ninja -C "$build" -j "$jobs" c++ocamlc
  new="$build/c++ocamlc"
  # the same libzstd as the runtime (compressed output is libzstd's)
  if [ -n "$(zstd_libs)" ] && command -v ldd >/dev/null; then
    zr=$(ldd "$bin/ocamlrun" 2>/dev/null | sed -n 's/.*libzstd[^ ]* => \([^ ]*\).*/\1/p')
    zc=$(ldd "$new" 2>/dev/null | sed -n 's/.*libzstd[^ ]* => \([^ ]*\).*/\1/p')
    if [ -n "$zr" ] && [ "$(readlink -f "$zr")" != "$(readlink -f "$zc")" ]; then
      die "libzstd mismatch: the runtime loads $zr, c++ocamlc $zc (compressed artifacts would differ)"
    fi
  fi
  # installed in place, then checked against the stock compiler; any
  # failure puts the stock one back
  cp "$new" "$bin/ocamlc.opt.cxx"
  mv -f "$bin/ocamlc.opt.cxx" "$bin/ocamlc.opt"
  restore() { cp "$bin/ocamlc.stock" "$bin/ocamlc.opt"; die "$1"; }
  t=$(mktemp -d)
  "$bin/ocamlc.stock" -config > "$t/stock.config"
  "$bin/ocamlc.opt" -config > "$t/cxx.config" || restore "c++ocamlc -config failed"
  cmp -s "$t/stock.config" "$t/cxx.config" || { diff "$t/stock.config" "$t/cxx.config" >&2 || true; restore "c++ocamlc's -config differs from the stock ocamlc's"; }
  printf 'let () = print_endline (String.concat " " ["hello"; "from"; "c++ocamlc"])\n' > "$t/hello.ml"
  ( cd "$t" && "$bin/ocamlc" hello.ml -o hello.byte && "$bin/ocamlrun" ./hello.byte > out ) ||
    restore "c++ocamlc could not compile and run a program"
  [ "$(cat "$t/out")" = "hello from c++ocamlc" ] || restore "the compiled program printed the wrong thing"
  rm -rf "$t"
  say "c++ocamlc installed as $bin/ocamlc.opt (the stock compiler is $bin/ocamlc.stock)"
}

case "${1:-}" in
  build) do_build "${2:-1}" ;;
  install) do_install "$2" "${3:-1}" ;;
  *) die "usage: build-cxx.sh build <jobs> | install <prefix> <jobs>" ;;
esac
