#!/bin/sh
# c++ocamlc and c++ocamlopt as an opam switch's ocamlc and ocamlopt: the
# step ocaml-variants.opam runs when ocaml-option-cxx is installed
# (cxx/INSTALL.md).
#
#   build-cxx.sh <prefix> <jobs>
#     in the build stage, in the source tree after `make` and
#     `make INSTALL_MODE=opam install` (which wrote ocaml-variants.install):
#     1. the tree installed into a stage (make install DESTDIR=): the
#        installation is --with-relative-libdir, so a staged copy resolves
#        its standard library as the real one will;
#     2. c++ocamlc and c++ocamlopt built by cxx/Makefile with the host's C++
#        compiler (CXX, default g++ >= 13) and the vendored mimalloc, its
#        driver tables generated from the staged OCaml
#        (Config, Main_args, warnings -- cxx/harness/gen_driver_tables.sh
#        INSTALL=), linking the installation's shared libzstd when its OCaml
#        compresses;
#     3. checked in the stage: the same libzstd file as the runtime's,
#        `-config` identical to the stock compilers', a program compiled and
#        run; c++ocamlopt's .cmx, .o and executable identical to the stock
#        ocamlopt's (c++ocamlopt is installed only for the configurations
#        its back ends support: non-flambda amd64 Linux, arm64 macOS);
#     4. ocaml-variants.install rewritten so that opam installs c++ocamlc as
#        bin/ocamlc.opt (bin/ocamlc points at it) and the stock compiler as
#        bin/ocamlc.stock; likewise c++ocamlopt as bin/ocamlopt.opt, the
#        stock one as bin/ocamlopt.stock.
set -eu
here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/../.." && pwd)
build="$root/cxx/_opam_build"
say() { echo "build-cxx.sh: $*" >&2; }
die() { say "error: $*"; exit 1; }

zstd_libs() { sed -n 's/^ZSTD_LIBS=//p' "$root/Makefile.config"; }

# the shared libzstd an executable loads (ldd; macOS: otool -L), its file
# with every symbolic link resolved (readlink -f), a shared library's suffix
libzstd_of() {
  if [ "$(uname -s)" = Darwin ]; then
    otool -L "$1" 2>/dev/null | sed -n 's|^[[:space:]]*\([^ ]*libzstd[^ ]*\) (.*|\1|p' | head -1
  else
    ldd "$1" 2>/dev/null | sed -n 's/.*libzstd[^ ]* => \([^ ]*\).*/\1/p' | head -1
  fi
}
resolve() { perl -MCwd=abs_path -e 'print abs_path($ARGV[0])' "$1"; }
if [ "$(uname -s)" = Darwin ]; then so_ext=dylib; else so_ext=so; fi

make_zstd_args() {  # <staged bin dir>
  if [ -n "$(zstd_libs)" ]; then
    # the very libzstd the installation's runtime loads (same compressor
    # code, hence the same bytes), and zstd.h where the C compiler that
    # built the runtime finds it
    so=$(libzstd_of "$1/ocamlrun")
    [ -n "$so" ] && [ -e "$so" ] || so=$("${CC:-cc}" -print-file-name=libzstd.$so_ext)
    inc=$(printf '#include <zstd.h>\n' | "${CC:-cc}" -E -x c - 2>/dev/null |
          sed -n 's|^# [0-9]* "\(.*\)/zstd\.h".*|\1|p' | head -1)
    [ -n "$inc" ] && [ -f "$inc/zstd.h" ] || die "this OCaml compresses with zstd but zstd.h was not found (install libzstd's development files)"
    [ -e "$so" ] || die "this OCaml compresses with zstd but its shared libzstd was not found"
    echo "ZSTD_CFLAGS=-I$inc ZSTD_LIBS=$(resolve "$so")"
  else
    echo "ZSTD_LIBS="
  fi
}

do_build() {
  prefix=$1 jobs=$2
  CXX=${CXX:-g++}
  command -v "$CXX" >/dev/null || die "no C++ compiler ($CXX); c++ocamlc needs a C++23 one (g++ >= 13, clang++ >= 18)"
  [ -x "$root/ocamlopt.opt" ] || die "c++ocamlc's configuration is generated by a native program: the native compiler is required"
  # 1. the stage
  stage="$root/_opam_stage"
  rm -rf "$stage"
  make -C "$root" install DESTDIR="$stage" >/dev/null
  sp="$stage$prefix"
  sbin="$sp/bin"
  [ -x "$sbin/ocamlc.opt" ] || die "the staged installation has no bin/ocamlc.opt"
  # 2. c++ocamlc for this installation
  INSTALL="$sp" "$root/cxx/harness/gen_driver_tables.sh"
  zstd_args=$(make_zstd_args "$sbin") || exit 1
  # the native back ends: non-flambda amd64 on Linux, arm64 on macOS
  arch=$("$sbin/ocamlopt.opt" -config-var architecture 2>/dev/null || true)
  case "$arch" in
    amd64) want_system=linux ;;
    arm64) want_system=macosx ;;
    *) want_system= ;;
  esac
  native=1
  if [ -z "$want_system" ]; then
    say "warning: architecture is $arch: c++ocamlopt supports only amd64 and arm64; keeping the stock ocamlopt"
    native=0
  fi
  for kv in system=$want_system flambda=false with_frame_pointers=false \
            asm_cfi_supported=true tsan=false; do
    [ $native = 1 ] || break
    v=$("$sbin/ocamlopt.opt" -config-var "${kv%%=*}" 2>/dev/null || true)
    if [ "$v" != "${kv#*=}" ]; then
      say "warning: ${kv%%=*} is $v: c++ocamlopt on $arch supports only ${kv#*=}; keeping the stock ocamlopt"
      native=0
    fi
  done
  targets="c++ocamlc"
  [ $native = 1 ] && targets="$targets c++ocamlopt"
  # shellcheck disable=SC2086
  make -C "$root/cxx" -j "$jobs" O=_opam_build CXX="$CXX" $zstd_args $targets
  new="$build/c++ocamlc"
  # 3. the checks, in the stage
  if [ -n "$(zstd_libs)" ] && { command -v ldd || command -v otool; } >/dev/null; then
    zr=$(libzstd_of "$sbin/ocamlrun")
    zc=$(libzstd_of "$new")
    if [ -n "$zr" ] && [ "$(resolve "$zr")" != "$(resolve "$zc")" ]; then
      die "libzstd mismatch: the runtime loads $zr, c++ocamlc $zc (compressed artifacts would differ)"
    fi
  fi
  cp "$sbin/ocamlc.opt" "$sbin/ocamlc.stock"
  cp "$new" "$sbin/ocamlc.opt"
  t=$(mktemp -d)
  "$sbin/ocamlc.stock" -config > "$t/stock.config"
  "$sbin/ocamlc.opt" -config > "$t/cxx.config" || die "c++ocamlc -config failed"
  if ! cmp -s "$t/stock.config" "$t/cxx.config"; then
    diff "$t/stock.config" "$t/cxx.config" >&2 || true
    die "c++ocamlc's -config differs from the stock ocamlc's"
  fi
  printf 'let () = print_endline (String.concat " " ["hello"; "from"; "c++ocamlc"])\n' > "$t/hello.ml"
  ( cd "$t" && "$sbin/ocamlc" hello.ml -o hello.byte && "$sbin/ocamlrun" ./hello.byte > out ) ||
    die "c++ocamlc could not compile and run a program"
  [ "$(cat "$t/out")" = "hello from c++ocamlc" ] || die "the compiled program printed the wrong thing"
  rm -rf "$t"
  if [ $native = 1 ]; then
    cp "$sbin/ocamlopt.opt" "$sbin/ocamlopt.stock"
    cp "$build/c++ocamlopt" "$sbin/ocamlopt.opt"
    t=$(mktemp -d)
    "$sbin/ocamlopt.stock" -config > "$t/stock.config"
    "$sbin/ocamlopt.opt" -config > "$t/cxx.config" || die "c++ocamlopt -config failed"
    if ! cmp -s "$t/stock.config" "$t/cxx.config"; then
      diff "$t/stock.config" "$t/cxx.config" >&2 || true
      die "c++ocamlopt's -config differs from the stock ocamlopt's"
    fi
    # the same outputs as the stock ocamlopt's, byte for byte (built one
    # after the other in the same directory: -g records it)
    printf 'let greet l = String.concat " " l\nlet () = Printf.printf "%%s\\n" (greet ["hello"; "from"])\n' > "$t/a.ml"
    printf 'let () = print_endline (A.greet ["c++ocamlopt"])\n' > "$t/b.ml"
    for c in stock opt; do
      ( cd "$t" && rm -f ./*.cm* ./*.o hello.exe &&
        "$sbin/ocamlopt.$c" -g -c a.ml && "$sbin/ocamlopt.$c" -g -c b.ml &&
        "$sbin/ocamlopt.$c" -g -o hello.exe a.cmx b.cmx && ./hello.exe > out.$c &&
        mkdir -p "$c" && cp a.cmx a.o b.cmx b.o hello.exe "$c/" ) ||
        die "ocamlopt.$c could not compile and run a program"
    done
    [ "$(cat "$t/out.opt")" = "$(printf 'hello from\nc++ocamlopt')" ] || die "the native program printed the wrong thing"
    for f in a.cmx a.o b.cmx b.o hello.exe; do
      cmp -s "$t/stock/$f" "$t/opt/$f" || die "c++ocamlopt's $f differs from the stock ocamlopt's"
    done
    rm -rf "$t"
  fi
  # 4. opam installs c++ocamlc as ocamlc.opt, the stock one as ocamlc.stock
  inst="$root/ocaml-variants.install"
  [ -f "$inst" ] || die "no ocaml-variants.install (make INSTALL_MODE=opam install must run first)"
  grep -q '^  "ocamlc.opt"$' "$inst" || die "ocaml-variants.install has no bin entry for ocamlc.opt"
  sed 's|^  "ocamlc.opt"$|  "cxx/_opam_build/c++ocamlc" {"ocamlc.opt"}\
  "ocamlc.opt" {"ocamlc.stock"}|' "$inst" > "$inst.new" && mv "$inst.new" "$inst"
  say "c++ocamlc will be installed as bin/ocamlc.opt (the stock compiler as bin/ocamlc.stock)"
  if [ $native = 1 ]; then
    grep -q '^  "ocamlopt.opt"$' "$inst" || die "ocaml-variants.install has no bin entry for ocamlopt.opt"
    sed 's|^  "ocamlopt.opt"$|  "cxx/_opam_build/c++ocamlopt" {"ocamlopt.opt"}\
  "ocamlopt.opt" {"ocamlopt.stock"}|' "$inst" > "$inst.new" && mv "$inst.new" "$inst"
    say "c++ocamlopt will be installed as bin/ocamlopt.opt (the stock compiler as bin/ocamlopt.stock)"
  fi
}

case "${1:-}" in
  /*) do_build "$1" "${2:-1}" ;;
  *) die "usage: build-cxx.sh <prefix> <jobs>" ;;
esac
