type _ t = Float : float t | String : string t | Int : int t
let h1 (type a) (t : a t) = match t with Float -> () | _ -> ()
let m1 = 0
let h2 (type a) (t : a t) = match t with Float -> () | String -> () | Int -> ()
let m2 = 0
let h3 (t : float t) = match t with Float -> ()
let m3 = 0
let h4 (type a) (t : a t) = match t with Float -> () | String -> ()
let m4 = 0
let h5 (type a) (t : a t) = match t with _ -> ()
let m5 = 0
let h6 (type a) (t : a t) = match t with Float -> () | _ -> ()
let m6 = 0
let h7 (type a) (t : a t) (u : a t) =
  match t, u with Float, Float -> () | _ -> ()
let m7 = 0
type e = E : 'a -> e
let h8 (e : e) = match e with E _ -> ()
let m8 = 0
let h9 (e : e) = match e with E x -> ignore x
let m9 = 0
let h10 (e : e) = match e with E x -> ignore x | _ -> ()
let m10 = 0
let h11 (type a) (t : a t) =
  match t with Float -> () | String -> () | Int -> () | _ -> ()
let m11 = 0
let h12 (type a) (t : a t) = match t with Int -> () | String -> () | Float -> ()
let m12 = 0
let h13 (type a) (t : a t) = match t with Int -> ()
let m13 = 0
let h14 (type a) (t : a t) = function Int -> ()
let m14 = 0
let h15 (type a) (t : a t) (x : a) = match t with Float -> () | String -> ()
let m15 = 0
